# Generated by Django 5.2.6 on 2026-07-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='token',
            field=models.TextField(blank=True, db_column='Token', null=True),
        ),
    ]
