# Generated by Django 5.2.6 on 2026-07-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIS', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='regionaladmin',
            index=models.Index(fields=['user'], name='idx_regionaladmin_user'),
        ),
        migrations.AddIndex(
            model_name='regionaladmin',
            index=models.Index(fields=['district'], name='idx_regionaladmin_district'),
        ),
        migrations.AddIndex(
            model_name='regionaladmin',
            index=models.Index(fields=['status'], name='idx_regionaladmin_status'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['user'], name='idx_teacher_user'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['center'], name='idx_teacher_center'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['status'], name='idx_teacher_status'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status'], name='idx_user_status'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='idx_user_role'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('email',), name='uc_user_email'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('phone_number',), name='uc_user_phone'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('enrolment_roll_id',), name='uc_user_enrolment'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
    ]
