# Generated by Django 5.2.6 on 2026-07-10 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIS', '0002_teacher_token'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VersiionControl',
            new_name='VersionControl',
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_on']},
        ),
        migrations.RemoveField(
            model_name='center',
            name='district_id',
        ),
        migrations.RemoveField(
            model_name='center',
            name='panchayat_id',
        ),
        migrations.RemoveField(
            model_name='center',
            name='vidhan_sabha_id',
        ),
        migrations.RemoveField(
            model_name='center',
            name='village_id',
        ),
        migrations.RemoveField(
            model_name='centerassignuser',
            name='center_id',
        ),
        migrations.RemoveField(
            model_name='centerlog',
            name='center_id',
        ),
        migrations.RemoveField(
            model_name='classcancelbyteacher',
            name='center_id',
        ),
        migrations.RemoveField(
            model_name='classdetail',
            name='center_id',
        ),
        migrations.RemoveField(
            model_name='classdetail',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='classdetail',
            name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='classmodel',
            name='center_id',
        ),
        migrations.RemoveField(
            model_name='holidaycenter',
            name='center_id',
        ),
        migrations.RemoveField(
            model_name='holidaycenter',
            name='holiday_id',
        ),
        migrations.RemoveField(
            model_name='holidays',
            name='center_id',
        ),
        migrations.RemoveField(
            model_name='panchayat',
            name='district_id',
        ),
        migrations.RemoveField(
            model_name='panchayat',
            name='vidhan_sabha_id',
        ),
        migrations.RemoveField(
            model_name='regionaladmin',
            name='center_id',
        ),
        migrations.RemoveField(
            model_name='regionaladmin',
            name='district_id',
        ),
        migrations.RemoveField(
            model_name='regionaladmin',
            name='panchayat_id',
        ),
        migrations.RemoveField(
            model_name='regionaladmin',
            name='vidhan_sabha_id',
        ),
        migrations.RemoveField(
            model_name='regionaladmin',
            name='village_id',
        ),
        migrations.RemoveField(
            model_name='regionaladminpanchayat',
            name='panchayat_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='center_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='district_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='panchayat_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='vidhan_sabha_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='village_id',
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='center_id',
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='center_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='district_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='panchayat_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='vidhan_sabha_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='village_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='district_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='panchayat_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vidhan_sabha_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='village_id',
        ),
        migrations.RemoveField(
            model_name='vidhansabha',
            name='district_id',
        ),
        migrations.RemoveField(
            model_name='village',
            name='district_id',
        ),
        migrations.RemoveField(
            model_name='village',
            name='panchayat_id',
        ),
        migrations.RemoveField(
            model_name='village',
            name='vidhan_sabha_id',
        ),
        migrations.AddField(
            model_name='center',
            name='district',
            field=models.ForeignKey(blank=True, db_column='DistrictId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centers', to='APIS.district'),
        ),
        migrations.AddField(
            model_name='center',
            name='panchayat',
            field=models.ForeignKey(blank=True, db_column='PanchayatId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centers', to='APIS.panchayat'),
        ),
        migrations.AddField(
            model_name='center',
            name='vidhan_sabha',
            field=models.ForeignKey(blank=True, db_column='VidhanSabhaId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centers', to='APIS.vidhansabha'),
        ),
        migrations.AddField(
            model_name='center',
            name='village',
            field=models.ForeignKey(blank=True, db_column='VillageId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centers', to='APIS.village'),
        ),
        migrations.AddField(
            model_name='centerassignuser',
            name='center',
            field=models.ForeignKey(blank=True, db_column='CenterId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='center_assign_users', to='APIS.center'),
        ),
        migrations.AddField(
            model_name='centerlog',
            name='center',
            field=models.ForeignKey(blank=True, db_column='CenterId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='center_logs', to='APIS.center'),
        ),
        migrations.AddField(
            model_name='classcancelbyteacher',
            name='center',
            field=models.ForeignKey(blank=True, db_column='CenterId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_cancel_by_teachers', to='APIS.center'),
        ),
        migrations.AddField(
            model_name='classdetail',
            name='center',
            field=models.ForeignKey(blank=True, db_column='CenterId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_details', to='APIS.center'),
        ),
        migrations.AddField(
            model_name='classdetail',
            name='class_obj',
            field=models.ForeignKey(blank=True, db_column='ClassId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_details', to='APIS.classmodel'),
        ),
        migrations.AddField(
            model_name='classdetail',
            name='student',
            field=models.ForeignKey(blank=True, db_column='StudentId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_details', to='APIS.student'),
        ),
        migrations.AddField(
            model_name='classdetail',
            name='teacher',
            field=models.ForeignKey(blank=True, db_column='TeacherId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_details', to='APIS.teacher'),
        ),
        migrations.AddField(
            model_name='classmodel',
            name='center',
            field=models.ForeignKey(blank=True, db_column='CenterId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='APIS.center'),
        ),
        migrations.AddField(
            model_name='holidaycenter',
            name='center',
            field=models.ForeignKey(blank=True, db_column='CenterId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holiday_centers', to='APIS.center'),
        ),
        migrations.AddField(
            model_name='holidaycenter',
            name='holiday',
            field=models.ForeignKey(blank=True, db_column='HolidayId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holiday_centers', to='APIS.holidays'),
        ),
        migrations.AddField(
            model_name='holidays',
            name='center',
            field=models.ForeignKey(blank=True, db_column='CenterId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holidays', to='APIS.center'),
        ),
        migrations.AddField(
            model_name='panchayat',
            name='district',
            field=models.ForeignKey(blank=True, db_column='DistrictId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panchayats', to='APIS.district'),
        ),
        migrations.AddField(
            model_name='panchayat',
            name='vidhan_sabha',
            field=models.ForeignKey(blank=True, db_column='VidhanSabhaId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panchayats', to='APIS.vidhansabha'),
        ),
        migrations.AddField(
            model_name='regionaladmin',
            name='center',
            field=models.ForeignKey(blank=True, db_column='CenterId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regional_admins', to='APIS.center'),
        ),
        migrations.AddField(
            model_name='regionaladmin',
            name='district',
            field=models.ForeignKey(blank=True, db_column='DistrictId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regional_admins', to='APIS.district'),
        ),
        migrations.AddField(
            model_name='regionaladmin',
            name='panchayat',
            field=models.ForeignKey(blank=True, db_column='PanchayatId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regional_admins', to='APIS.panchayat'),
        ),
        migrations.AddField(
            model_name='regionaladmin',
            name='vidhan_sabha',
            field=models.ForeignKey(blank=True, db_column='VidhanSabhaId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regional_admins', to='APIS.vidhansabha'),
        ),
        migrations.AddField(
            model_name='regionaladmin',
            name='village',
            field=models.ForeignKey(blank=True, db_column='VillageId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regional_admins', to='APIS.village'),
        ),
        migrations.AddField(
            model_name='regionaladminpanchayat',
            name='panchayat',
            field=models.ForeignKey(blank=True, db_column='PanchayatId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regional_admin_panchayats', to='APIS.panchayat'),
        ),
        migrations.AddField(
            model_name='student',
            name='center',
            field=models.ForeignKey(blank=True, db_column='CenterId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='APIS.center'),
        ),
        migrations.AddField(
            model_name='student',
            name='district',
            field=models.ForeignKey(blank=True, db_column='DistrictId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='APIS.district'),
        ),
        migrations.AddField(
            model_name='student',
            name='panchayat',
            field=models.ForeignKey(blank=True, db_column='PanchayatId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='APIS.panchayat'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, db_column='SchoolId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='APIS.school'),
        ),
        migrations.AddField(
            model_name='student',
            name='vidhan_sabha',
            field=models.ForeignKey(blank=True, db_column='VidhanSabhaId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='APIS.vidhansabha'),
        ),
        migrations.AddField(
            model_name='student',
            name='village',
            field=models.ForeignKey(blank=True, db_column='VillageId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='APIS.village'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='center',
            field=models.ForeignKey(blank=True, db_column='CenterId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='APIS.center'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='class_obj',
            field=models.ForeignKey(blank=True, db_column='ClassId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='APIS.classmodel'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='student',
            field=models.ForeignKey(blank=True, db_column='StudentId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='APIS.student'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='center',
            field=models.ForeignKey(blank=True, db_column='CenterId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='APIS.center'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='district',
            field=models.ForeignKey(blank=True, db_column='DistrictId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='APIS.district'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='panchayat',
            field=models.ForeignKey(blank=True, db_column='PanchayatId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='APIS.panchayat'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='vidhan_sabha',
            field=models.ForeignKey(blank=True, db_column='VidhanSabhaId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='APIS.vidhansabha'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='village',
            field=models.ForeignKey(blank=True, db_column='VillageId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='APIS.village'),
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.ForeignKey(blank=True, db_column='DistrictId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='APIS.district'),
        ),
        migrations.AddField(
            model_name='user',
            name='panchayat',
            field=models.ForeignKey(blank=True, db_column='PanchayatId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='APIS.panchayat'),
        ),
        migrations.AddField(
            model_name='user',
            name='vidhan_sabha',
            field=models.ForeignKey(blank=True, db_column='VidhanSabhaId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='APIS.vidhansabha'),
        ),
        migrations.AddField(
            model_name='user',
            name='village',
            field=models.ForeignKey(blank=True, db_column='VillageId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='APIS.village'),
        ),
        migrations.AddField(
            model_name='vidhansabha',
            name='district',
            field=models.ForeignKey(blank=True, db_column='DistrictId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vidhan_sabhas', to='APIS.district'),
        ),
        migrations.AddField(
            model_name='village',
            name='district',
            field=models.ForeignKey(blank=True, db_column='DistrictId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='villages', to='APIS.district'),
        ),
        migrations.AddField(
            model_name='village',
            name='panchayat',
            field=models.ForeignKey(blank=True, db_column='PanchayatId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='villages', to='APIS.panchayat'),
        ),
        migrations.AddField(
            model_name='village',
            name='vidhan_sabha',
            field=models.ForeignKey(blank=True, db_column='VidhanSabhaId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='villages', to='APIS.vidhansabha'),
        ),
        migrations.AlterField(
            model_name='center',
            name='center_guid_id',
            field=models.CharField(blank=True, db_column='CenterGuidId', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='center_name',
            field=models.CharField(blank=True, db_column='CenterName', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='classdetail',
            name='class_guid_id',
            field=models.UUIDField(db_column='ClassGuidId', unique=True),
        ),
        migrations.AlterField(
            model_name='classmodel',
            name='class_enrolment_id',
            field=models.CharField(blank=True, db_column='ClassEnrolmentId', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='district_guid_id',
            field=models.UUIDField(db_column='DistrictGuidId', unique=True),
        ),
        migrations.AlterField(
            model_name='panchayat',
            name='panchayat_guid_id',
            field=models.UUIDField(db_column='PanchayatGuidId', unique=True),
        ),
        migrations.AlterField(
            model_name='regionaladmin',
            name='email',
            field=models.EmailField(blank=True, db_column='Email', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='regionaladmin',
            name='phone_number',
            field=models.CharField(blank=True, db_column='PhoneNumber', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='regionaladmin',
            name='regional_admin_guid_id',
            field=models.UUIDField(db_column='RegionalAdminGuidId', unique=True),
        ),
        migrations.AlterField(
            model_name='schoolname',
            name='school_name',
            field=models.CharField(db_column='SchoolName', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, db_column='Email', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_id',
            field=models.CharField(blank=True, db_column='EnrollmentId', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, db_column='PhoneNumber', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, db_column='Email', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, db_column='PhoneNumber', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_guid_id',
            field=models.UUIDField(db_column='TeacherGuidId', unique=True),
        ),
        migrations.AlterField(
            model_name='teacheractivitylog',
            name='teacher_acivity_guid_id',
            field=models.UUIDField(db_column='TeacherAcivityGuidId', unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_column='Email', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='enrolment_roll_id',
            field=models.CharField(blank=True, db_column='EnrolmentRollId', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, db_column='PhoneNumber', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vidhansabha',
            name='vidhan_sabha_guid_id',
            field=models.UUIDField(db_column='VidhanSabhaGuidId', unique=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='village_guid_id',
            field=models.UUIDField(db_column='VillageGuidId', unique=True),
        ),
        migrations.AddIndex(
            model_name='center',
            index=models.Index(fields=['district'], name='idx_center_district'),
        ),
        migrations.AddIndex(
            model_name='center',
            index=models.Index(fields=['panchayat'], name='idx_center_panchayat'),
        ),
        migrations.AddIndex(
            model_name='center',
            index=models.Index(fields=['vidhan_sabha'], name='idx_center_vidhansabha'),
        ),
        migrations.AddIndex(
            model_name='center',
            index=models.Index(fields=['village'], name='idx_center_village'),
        ),
        migrations.AddIndex(
            model_name='center',
            index=models.Index(fields=['status'], name='idx_center_status'),
        ),
        migrations.AddIndex(
            model_name='center',
            index=models.Index(fields=['class_status'], name='idx_center_class_status'),
        ),
        migrations.AddIndex(
            model_name='centerassignuser',
            index=models.Index(fields=['users_id'], name='idx_centerassignuser_users'),
        ),
        migrations.AddIndex(
            model_name='centerassignuser',
            index=models.Index(fields=['center'], name='idx_centerassignuser_center'),
        ),
        migrations.AddIndex(
            model_name='centerassignuser',
            index=models.Index(fields=['type'], name='idx_centerassignuser_type'),
        ),
        migrations.AddIndex(
            model_name='centerlog',
            index=models.Index(fields=['center'], name='idx_centerlog_center'),
        ),
        migrations.AddIndex(
            model_name='centerlog',
            index=models.Index(fields=['user_id'], name='idx_centerlog_user'),
        ),
        migrations.AddIndex(
            model_name='classcancelbyteacher',
            index=models.Index(fields=['center'], name='idx_classcancel_center'),
        ),
        migrations.AddIndex(
            model_name='classcancelbyteacher',
            index=models.Index(fields=['user_id'], name='idx_classcancel_user'),
        ),
        migrations.AddIndex(
            model_name='classcancelbyteacher',
            index=models.Index(fields=['starting_date'], name='idx_classcancel_start_date'),
        ),
        migrations.AddIndex(
            model_name='classdetail',
            index=models.Index(fields=['class_guid_id'], name='idx_classdetail_guid'),
        ),
        migrations.AddIndex(
            model_name='classdetail',
            index=models.Index(fields=['student'], name='idx_classdetail_student'),
        ),
        migrations.AddIndex(
            model_name='classdetail',
            index=models.Index(fields=['teacher'], name='idx_classdetail_teacher'),
        ),
        migrations.AddIndex(
            model_name='classdetail',
            index=models.Index(fields=['center'], name='idx_classdetail_center'),
        ),
        migrations.AddIndex(
            model_name='classdetail',
            index=models.Index(fields=['class_obj'], name='idx_classdetail_class'),
        ),
        migrations.AddIndex(
            model_name='classmodel',
            index=models.Index(fields=['center'], name='idx_class_center'),
        ),
        migrations.AddIndex(
            model_name='classmodel',
            index=models.Index(fields=['status'], name='idx_class_status'),
        ),
        migrations.AddIndex(
            model_name='classmodel',
            index=models.Index(fields=['users_id'], name='idx_class_users'),
        ),
        migrations.AddIndex(
            model_name='classmodel',
            index=models.Index(fields=['sub_status'], name='idx_class_sub_status'),
        ),
        migrations.AddIndex(
            model_name='classmodel',
            index=models.Index(fields=['started_date'], name='idx_class_started_date'),
        ),
        migrations.AddIndex(
            model_name='concern',
            index=models.Index(fields=['users_id'], name='idx_concern_users'),
        ),
        migrations.AddIndex(
            model_name='concern',
            index=models.Index(fields=['type'], name='idx_concern_type'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['status'], name='idx_district_status'),
        ),
        migrations.AddIndex(
            model_name='holidaycenter',
            index=models.Index(fields=['holiday'], name='idx_holidaycenter_holiday'),
        ),
        migrations.AddIndex(
            model_name='holidaycenter',
            index=models.Index(fields=['center'], name='idx_holidaycenter_center'),
        ),
        migrations.AddIndex(
            model_name='holidays',
            index=models.Index(fields=['center'], name='idx_holidays_center'),
        ),
        migrations.AddIndex(
            model_name='holidays',
            index=models.Index(fields=['status'], name='idx_holidays_status'),
        ),
        migrations.AddIndex(
            model_name='holidays',
            index=models.Index(fields=['start_date', 'end_date'], name='idx_holidays_dates'),
        ),
        migrations.AddIndex(
            model_name='panchayat',
            index=models.Index(fields=['district'], name='idx_panchayat_district'),
        ),
        migrations.AddIndex(
            model_name='panchayat',
            index=models.Index(fields=['vidhan_sabha'], name='idx_panchayat_vidhansabha'),
        ),
        migrations.AddIndex(
            model_name='panchayat',
            index=models.Index(fields=['status'], name='idx_panchayat_status'),
        ),
        migrations.AddIndex(
            model_name='regionaladmin',
            index=models.Index(fields=['district'], name='idx_regionaladmin_district'),
        ),
        migrations.AddIndex(
            model_name='regionaladmin',
            index=models.Index(fields=['panchayat'], name='idx_regionaladmin_panchayat'),
        ),
        migrations.AddIndex(
            model_name='regionaladmin',
            index=models.Index(fields=['vidhan_sabha'], name='idx_regionaladmin_vidhansabha'),
        ),
        migrations.AddIndex(
            model_name='regionaladmin',
            index=models.Index(fields=['village'], name='idx_regionaladmin_village'),
        ),
        migrations.AddIndex(
            model_name='regionaladmin',
            index=models.Index(fields=['center'], name='idx_regionaladmin_center'),
        ),
        migrations.AddIndex(
            model_name='regionaladmin',
            index=models.Index(fields=['status'], name='idx_regionaladmin_status'),
        ),
        migrations.AddIndex(
            model_name='regionaladminpanchayat',
            index=models.Index(fields=['users_id'], name='idx_regadminpanchayat_users'),
        ),
        migrations.AddIndex(
            model_name='regionaladminpanchayat',
            index=models.Index(fields=['panchayat'], name='idx_regadminpnhyt_panchayat'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['district'], name='idx_student_district'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['panchayat'], name='idx_student_panchayat'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['vidhan_sabha'], name='idx_student_vidhansabha'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['village'], name='idx_student_village'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['center'], name='idx_student_center'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status'], name='idx_student_status'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['active_class_status'], name='idx_student_active_class'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['class_obj'], name='idx_attendance_class'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['student'], name='idx_attendance_student'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['center'], name='idx_attendance_center'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['scan_date'], name='idx_attendance_scan_date'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['user_id'], name='idx_attendance_user'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['district'], name='idx_teacher_district'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['panchayat'], name='idx_teacher_panchayat'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['vidhan_sabha'], name='idx_teacher_vidhansabha'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['village'], name='idx_teacher_village'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['center'], name='idx_teacher_center'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['status'], name='idx_teacher_status'),
        ),
        migrations.AddIndex(
            model_name='teacheractivitylog',
            index=models.Index(fields=['teacher_acivity_guid_id'], name='idx_teacheractivity_guid'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['district'], name='idx_user_district'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['panchayat'], name='idx_user_panchayat'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['vidhan_sabha'], name='idx_user_vidhansabha'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['village'], name='idx_user_village'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status'], name='idx_user_status'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['type'], name='idx_user_type'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role_id'], name='idx_user_role'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['user_id'], name='idx_useractivity_user'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['activity_date'], name='idx_useractivity_date'),
        ),
        migrations.AddIndex(
            model_name='versioncontrol',
            index=models.Index(fields=['app_id'], name='idx_versioncontrol_app'),
        ),
        migrations.AddIndex(
            model_name='versioncontrol',
            index=models.Index(fields=['status'], name='idx_versioncontrol_status'),
        ),
        migrations.AddIndex(
            model_name='vidhansabha',
            index=models.Index(fields=['district'], name='idx_vidhansabha_district'),
        ),
        migrations.AddIndex(
            model_name='vidhansabha',
            index=models.Index(fields=['status'], name='idx_vidhansabha_status'),
        ),
        migrations.AddIndex(
            model_name='village',
            index=models.Index(fields=['district'], name='idx_village_district'),
        ),
        migrations.AddIndex(
            model_name='village',
            index=models.Index(fields=['panchayat'], name='idx_village_panchayat'),
        ),
        migrations.AddIndex(
            model_name='village',
            index=models.Index(fields=['vidhan_sabha'], name='idx_village_vidhansabha'),
        ),
        migrations.AddIndex(
            model_name='village',
            index=models.Index(fields=['status'], name='idx_village_status'),
        ),
        migrations.AddConstraint(
            model_name='center',
            constraint=models.UniqueConstraint(fields=('center_name',), name='uc_center_name'),
        ),
        migrations.AddConstraint(
            model_name='center',
            constraint=models.UniqueConstraint(fields=('center_guid_id',), name='uc_center_guid'),
        ),
        migrations.AddConstraint(
            model_name='classdetail',
            constraint=models.UniqueConstraint(fields=('class_guid_id',), name='uc_classdetail_guid'),
        ),
        migrations.AddConstraint(
            model_name='classmodel',
            constraint=models.UniqueConstraint(fields=('class_enrolment_id',), name='uc_class_enrolment'),
        ),
        migrations.AddConstraint(
            model_name='regionaladmin',
            constraint=models.UniqueConstraint(fields=('regional_admin_guid_id',), name='uc_regionaladmin_guid'),
        ),
        migrations.AddConstraint(
            model_name='regionaladmin',
            constraint=models.UniqueConstraint(fields=('email',), name='uc_regionaladmin_email'),
        ),
        migrations.AddConstraint(
            model_name='regionaladmin',
            constraint=models.UniqueConstraint(fields=('phone_number',), name='uc_regionaladmin_phone'),
        ),
        migrations.AddConstraint(
            model_name='school',
            constraint=models.UniqueConstraint(fields=('school_name',), name='uc_school_name'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('enrollment_id',), name='uc_student_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('email',), name='uc_student_email'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('phone_number',), name='uc_student_phone'),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(fields=('teacher_guid_id',), name='uc_teacher_guid'),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(fields=('email',), name='uc_teacher_email'),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(fields=('phone_number',), name='uc_teacher_phone'),
        ),
        migrations.AddConstraint(
            model_name='teacheractivitylog',
            constraint=models.UniqueConstraint(fields=('teacher_acivity_guid_id',), name='uc_teacheractivity_guid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('email',), name='uc_user_email'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('phone_number',), name='uc_user_phone'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('enrolment_roll_id',), name='uc_user_enrolment'),
        ),
        migrations.AlterModelTable(
            name='versioncontrol',
            table='VersionControl',
        ),
    ]
