# Generated by Django 5.2.6 on 2026-07-16 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIS', '0002_regionaladmin_idx_regionaladmin_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, db_column='UserId', null=True)),
                ('action', models.CharField(blank=True, db_column='Action', max_length=50, null=True)),
                ('module', models.CharField(blank=True, db_column='Module', max_length=50, null=True)),
                ('record_id', models.IntegerField(blank=True, db_column='RecordId', null=True)),
                ('data', models.TextField(blank=True, db_column='Data', null=True)),
                ('ip_address', models.CharField(blank=True, db_column='IpAddress', max_length=50, null=True)),
                ('created_on', models.DateTimeField(blank=True, db_column='CreatedOn', null=True)),
            ],
            options={
                'db_table': 'ActivityLog',
            },
        ),
        migrations.RemoveIndex(
            model_name='regionaladminpanchayat',
            name='idx_regadminpanchayat_users',
        ),
        migrations.RenameIndex(
            model_name='regionaladminpanchayat',
            new_name='idx_regadmpnhyt_panchayat',
            old_name='idx_regadminpnhyt_panchayat',
        ),
        migrations.RemoveField(
            model_name='regionaladminpanchayat',
            name='users_id',
        ),
        migrations.AddField(
            model_name='regionaladminpanchayat',
            name='regional_admin',
            field=models.ForeignKey(blank=True, db_column='RegionalAdminId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regional_admin_panchayats', to='APIS.regionaladmin'),
        ),
        migrations.AddIndex(
            model_name='regionaladminpanchayat',
            index=models.Index(fields=['regional_admin'], name='idx_regadmpnhyt_regaladm'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user_id'], name='idx_activitylog_user'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['module'], name='idx_activitylog_module'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['created_on'], name='idx_activitylog_created_on'),
        ),
    ]
