# Generated by Django 5.2.6 on 2026-07-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIS', '0003_rename_versiioncontrol_versioncontrol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classdetail',
            name='class_guid_id',
            field=models.CharField(db_column='ClassGuidId', max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='district_guid_id',
            field=models.CharField(db_column='DistrictGuidId', max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='panchayat',
            name='panchayat_guid_id',
            field=models.CharField(db_column='PanchayatGuidId', max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='regionaladmin',
            name='regional_admin_guid_id',
            field=models.CharField(db_column='RegionalAdminGuidId', max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_guid_id',
            field=models.CharField(db_column='TeacherGuidId', max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='teacheractivitylog',
            name='teacher_acivity_guid_id',
            field=models.CharField(db_column='TeacherAcivityGuidId', max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='vidhansabha',
            name='vidhan_sabha_guid_id',
            field=models.CharField(db_column='VidhanSabhaGuidId', max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='village_guid_id',
            field=models.CharField(db_column='VillageGuidId', max_length=36, unique=True),
        ),
    ]
