# Generated by Django 5.2.4 on 2026-07-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIS', '0003_activitylog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, db_column='Picture', null=True, upload_to='profile_pic/'),
        ),
    ]
