# Generated by Django 5.2.6 on 2026-07-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIS', '0004_alter_classdetail_class_guid_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='status',
            field=models.BooleanField(blank=True, db_column='Status', default=True, null=True),
        ),
        migrations.AddField(
            model_name='centerassignuser',
            name='status',
            field=models.BooleanField(blank=True, db_column='Status', default=True, null=True),
        ),
        migrations.AddField(
            model_name='centerlog',
            name='status',
            field=models.BooleanField(blank=True, db_column='Status', default=True, null=True),
        ),
        migrations.AddField(
            model_name='classcancelbyteacher',
            name='status',
            field=models.BooleanField(blank=True, db_column='Status', default=True, null=True),
        ),
        migrations.AddField(
            model_name='classdetail',
            name='status',
            field=models.BooleanField(blank=True, db_column='Status', default=True, null=True),
        ),
        migrations.AddField(
            model_name='concern',
            name='status',
            field=models.BooleanField(blank=True, db_column='Status', default=True, null=True),
        ),
        migrations.AddField(
            model_name='holidaycenter',
            name='status',
            field=models.BooleanField(blank=True, db_column='Status', default=True, null=True),
        ),
        migrations.AddField(
            model_name='regionaladminpanchayat',
            name='status',
            field=models.BooleanField(blank=True, db_column='Status', default=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='status',
            field=models.BooleanField(blank=True, db_column='Status', default=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolname',
            name='status',
            field=models.BooleanField(blank=True, db_column='Status', default=True, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='status',
            field=models.BooleanField(blank=True, db_column='Status', default=True, null=True),
        ),
        migrations.AddField(
            model_name='teacheractivitylog',
            name='status',
            field=models.BooleanField(blank=True, db_column='Status', default=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='status',
            field=models.BooleanField(blank=True, db_column='Status', default=True, null=True),
        ),
    ]
