# Generated by Django 5.2.4 on 2026-07-20 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIS', '0004_alter_user_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterLocationVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_latitude', models.DecimalField(blank=True, db_column='OldLatitude', decimal_places=7, max_digits=10, null=True)),
                ('old_longitude', models.DecimalField(blank=True, db_column='OldLongitude', decimal_places=7, max_digits=10, null=True)),
                ('new_latitude', models.DecimalField(db_column='NewLatitude', decimal_places=7, max_digits=10)),
                ('new_longitude', models.DecimalField(db_column='NewLongitude', decimal_places=7, max_digits=10)),
                ('verified_at', models.DateTimeField(auto_now_add=True, db_column='VerifiedAt')),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
            ],
            options={
                'db_table': 'CenterLocationVerification',
            },
        ),
        migrations.CreateModel(
            name='StudentManualAttendanceLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_column='Year')),
                ('month', models.IntegerField(db_column='Month')),
                ('count', models.IntegerField(db_column='Count', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
            ],
            options={
                'db_table': 'StudentManualAttendanceLimit',
            },
        ),
        migrations.CreateModel(
            name='StudentQRCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_token', models.CharField(db_column='SecretToken', max_length=64)),
                ('qr_image_url', models.CharField(db_column='QRImageUrl', max_length=500)),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_column='GeneratedAt')),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('version', models.IntegerField(db_column='Version')),
            ],
            options={
                'db_table': 'StudentQRCode',
            },
        ),
        migrations.AddField(
            model_name='center',
            name='latitude',
            field=models.DecimalField(blank=True, db_column='Latitude', decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='location_status',
            field=models.CharField(choices=[('PENDING', 'Location Verification Pending'), ('VERIFIED', 'Location Verified')], db_column='LocationStatus', default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='center',
            name='location_verification_notes',
            field=models.TextField(blank=True, db_column='LocationVerificationNotes', null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='location_verified_at',
            field=models.DateTimeField(blank=True, db_column='LocationVerifiedAt', null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='location_verified_by',
            field=models.ForeignKey(blank=True, db_column='LocationVerifiedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, to='APIS.user'),
        ),
        migrations.AddField(
            model_name='center',
            name='longitude',
            field=models.DecimalField(blank=True, db_column='Longitude', decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='classmodel',
            name='absent_count',
            field=models.IntegerField(db_column='AbsentCount', default=0),
        ),
        migrations.AddField(
            model_name='classmodel',
            name='classroom_photo_url',
            field=models.CharField(blank=True, db_column='ClassroomPhotoUrl', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='classmodel',
            name='closed_by',
            field=models.ForeignKey(blank=True, db_column='ClosedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, to='APIS.user'),
        ),
        migrations.AddField(
            model_name='classmodel',
            name='end_time',
            field=models.DateTimeField(blank=True, db_column='EndTime', null=True),
        ),
        migrations.AddField(
            model_name='classmodel',
            name='present_count',
            field=models.IntegerField(db_column='PresentCount', default=0),
        ),
        migrations.AddField(
            model_name='classmodel',
            name='session_closed',
            field=models.BooleanField(db_column='SessionClosed', default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='qr_code_generated_at',
            field=models.DateTimeField(blank=True, db_column='QRCodeGeneratedAt', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='qr_code_image_url',
            field=models.CharField(blank=True, db_column='QRCodeImageUrl', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='qr_code_secret',
            field=models.CharField(blank=True, db_column='QRCodeSecret', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='qr_code_version',
            field=models.IntegerField(db_column='QRCodeVersion', default=1),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='attendance_type',
            field=models.CharField(choices=[('QR_AUTO', 'QR Auto Scan'), ('QR_MANUAL', 'QR Manual Entry'), ('MANUAL', 'Manual Fallback')], db_column='AttendanceType', default='QR_AUTO', max_length=20),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='captured_latitude',
            field=models.DecimalField(blank=True, db_column='CapturedLatitude', decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='captured_longitude',
            field=models.DecimalField(blank=True, db_column='CapturedLongitude', decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='device_info',
            field=models.CharField(blank=True, db_column='DeviceInfo', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='location_verified',
            field=models.BooleanField(db_column='LocationVerified', default=False),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='manual_reason',
            field=models.TextField(blank=True, db_column='ManualReason', null=True),
        ),
        migrations.AddIndex(
            model_name='center',
            index=models.Index(fields=['location_status'], name='idx_center_location_status'),
        ),
        migrations.AddIndex(
            model_name='classmodel',
            index=models.Index(fields=['session_closed'], name='idx_class_session_closed'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['attendance_type'], name='idx_attendance_type'),
        ),
        migrations.AddField(
            model_name='centerlocationverification',
            name='center',
            field=models.ForeignKey(db_column='CenterId', on_delete=django.db.models.deletion.CASCADE, to='APIS.center'),
        ),
        migrations.AddField(
            model_name='centerlocationverification',
            name='verified_by',
            field=models.ForeignKey(db_column='VerifiedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, to='APIS.user'),
        ),
        migrations.AddField(
            model_name='studentmanualattendancelimit',
            name='student',
            field=models.ForeignKey(db_column='StudentId', on_delete=django.db.models.deletion.CASCADE, to='APIS.student'),
        ),
        migrations.AddField(
            model_name='studentqrcode',
            name='generated_by',
            field=models.ForeignKey(blank=True, db_column='GeneratedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, to='APIS.user'),
        ),
        migrations.AddField(
            model_name='studentqrcode',
            name='student',
            field=models.ForeignKey(db_column='StudentId', on_delete=django.db.models.deletion.CASCADE, to='APIS.student'),
        ),
        migrations.AddIndex(
            model_name='centerlocationverification',
            index=models.Index(fields=['center', 'verified_at'], name='CenterLocat_CenterI_914c5b_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmanualattendancelimit',
            index=models.Index(fields=['student', 'year', 'month'], name='StudentManu_Student_047b68_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentmanualattendancelimit',
            unique_together={('student', 'year', 'month')},
        ),
        migrations.AddIndex(
            model_name='studentqrcode',
            index=models.Index(fields=['student', 'is_active'], name='StudentQRCo_Student_5eb403_idx'),
        ),
    ]
