# Generated by Django 5.2.6 on 2026-07-21 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIS', '0005_centerlocationverification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='location_verification_notes',
        ),
        migrations.RemoveField(
            model_name='classmodel',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='student',
            name='qr_code_generated_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='qr_code_image_url',
        ),
        migrations.RemoveField(
            model_name='student',
            name='qr_code_secret',
        ),
        migrations.RemoveField(
            model_name='student',
            name='qr_code_version',
        ),
        migrations.DeleteModel(
            name='StudentQRCode',
        ),
    ]
