# Generated by Django 5.2.6 on 2026-07-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIS', '0005_announcement_status_centerassignuser_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmodel',
            name='active_status',
            field=models.BooleanField(blank=True, db_column='active_status', default=True, null=True),
        ),
    ]
