# Generated by Django 5.2.4 on 2026-07-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIS', '0006_remove_center_location_verification_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='location_verified',
            field=models.BooleanField(blank=True, db_column='LocationVerified', default=False, null=True),
        ),
    ]
