# Generated by Django 5.2.6 on 2026-07-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIS', '0006_classmodel_active_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='status',
            field=models.BooleanField(blank=True, db_column='Status', default=True, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='status',
            field=models.BooleanField(blank=True, db_column='Status', default=True, null=True),
        ),
        migrations.AlterField(
            model_name='holidays',
            name='status',
            field=models.BooleanField(blank=True, db_column='Status', default=True, null=True),
        ),
        migrations.AlterField(
            model_name='panchayat',
            name='status',
            field=models.BooleanField(blank=True, db_column='Status', default=True, null=True),
        ),
        migrations.AlterField(
            model_name='regionaladmin',
            name='status',
            field=models.BooleanField(blank=True, db_column='Status', default=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.BooleanField(blank=True, db_column='Status', default=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='status',
            field=models.BooleanField(blank=True, db_column='Status', default=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.BooleanField(blank=True, db_column='Status', default=True, null=True),
        ),
        migrations.AlterField(
            model_name='vidhansabha',
            name='status',
            field=models.BooleanField(blank=True, db_column='Status', default=True, null=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='status',
            field=models.BooleanField(blank=True, db_column='Status', default=True, null=True),
        ),
    ]
