# Generated by Django 5.2.4 on 2026-07-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIS', '0007_alter_studentattendance_location_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmodel',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (2, 'Completed'), (3, 'Cancelled')], db_column='Status', null=True),
        ),
    ]
