# Generated by Django 5.2.6 on 2026-07-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIS', '0008_add_class_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='address',
            field=models.TextField(blank=True, db_column='Address', null=True),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='attendance_type',
            field=models.CharField(choices=[('AUTO', 'QR Auto Scan'), ('MANUAL', 'Manual Fallback')], db_column='AttendanceType', default='QR_AUTO', max_length=20),
        ),
    ]
