# Generated by Django 5.2.6 on 2026-07-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIS', '0009_center_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centerlocationverification',
            name='id',
            field=models.AutoField(db_column='Id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentmanualattendancelimit',
            name='id',
            field=models.AutoField(db_column='Id', primary_key=True, serialize=False),
        ),
    ]
