# Generated by Django 5.2.6 on 2026-07-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIS', '0010_alter_centerlocationverification_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll_number',
            field=models.IntegerField(blank=True, db_column='roll_number', null=True),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='attendance_type',
            field=models.CharField(choices=[('AUTO', 'QR Auto Scan'), ('MANUAL', 'Manual Fallback'), ('REGULAR', 'Regular')], db_column='AttendanceType', default='QR_AUTO', max_length=20),
        ),
    ]
