# Generated by Django 5.2.4 on 2026-08-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIS', '0011_student_roll_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebActivityLog',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, db_column='UserId', null=True)),
                ('user_name', models.CharField(blank=True, db_column='UserName', max_length=100, null=True)),
                ('role', models.CharField(blank=True, db_column='Role', max_length=50, null=True)),
                ('action', models.CharField(blank=True, db_column='Action', max_length=50, null=True)),
                ('module', models.CharField(blank=True, db_column='Module', max_length=50, null=True)),
                ('record_id', models.IntegerField(blank=True, db_column='RecordId', null=True)),
                ('record_name', models.CharField(blank=True, db_column='RecordName', max_length=200, null=True)),
                ('data', models.TextField(blank=True, db_column='Data', null=True)),
                ('ip_address', models.CharField(blank=True, db_column='IpAddress', max_length=50, null=True)),
                ('user_agent', models.TextField(blank=True, db_column='UserAgent', null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
            ],
            options={
                'db_table': 'WebActivityLog',
                'indexes': [models.Index(fields=['user_id'], name='idx_webactivitylog_user'), models.Index(fields=['module'], name='idx_webactivitylog_module'), models.Index(fields=['action'], name='idx_webactivitylog_action'), models.Index(fields=['created_on'], name='idx_webactivitylog_created_on')],
            },
        ),
    ]
