# Generated by Django 5.2.4 on 2026-08-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIS', '0012_webactivitylog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebActivityLog',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='message',
            field=models.TextField(blank=True, db_column='Message', null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='record_name',
            field=models.CharField(blank=True, db_column='RecordName', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='role',
            field=models.CharField(blank=True, db_column='Role', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user_agent',
            field=models.TextField(blank=True, db_column='UserAgent', null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user_name',
            field=models.CharField(blank=True, db_column='UserName', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedOn', null=True),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action'], name='idx_activitylog_action'),
        ),
    ]
