# Generated by Django 5.2.4 on 2026-08-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIS', '0013_delete_webactivitylog_activitylog_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centerassignuser',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Super Admin'), (2, 'Regional Admin'), (3, 'Teacher')], db_column='Type', null=True),
        ),
    ]
