# Generated by Django 5.2.6 on 2026-09-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIS', '0014_alter_centerassignuser_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classdetail',
            name='center',
        ),
        migrations.RemoveField(
            model_name='classdetail',
            name='class_obj',
        ),
        migrations.RemoveField(
            model_name='classdetail',
            name='student',
        ),
        migrations.RemoveField(
            model_name='classdetail',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Concern',
        ),
        migrations.RemoveField(
            model_name='holidaycenter',
            name='center',
        ),
        migrations.RemoveField(
            model_name='holidaycenter',
            name='holiday',
        ),
        migrations.DeleteModel(
            name='SchoolName',
        ),
        migrations.DeleteModel(
            name='TeacherActivityLog',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TestTable',
        ),
        migrations.DeleteModel(
            name='UserActivityLog',
        ),
        migrations.DeleteModel(
            name='VersionControl',
        ),
        migrations.RemoveConstraint(
            model_name='student',
            name='uc_student_phone',
        ),
        migrations.AddField(
            model_name='student',
            name='aadhar_number',
            field=models.CharField(blank=True, db_column='AadharNumber', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_image_url',
            field=models.CharField(blank=True, db_column='ProfileImageUrl', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_name',
            field=models.CharField(blank=True, db_column='SchoolName', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(blank=True, db_column='FullName', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, db_column='PhoneNumber', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.CharField(blank=True, db_column='ProfileImage', max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='ClassDetail',
        ),
        migrations.DeleteModel(
            name='HolidayCenter',
        ),
    ]
